default_platform(:ios)
xcode_version = "10.0"

platform :ios do
  before_all do |lane, options|
    xcversion(version: xcode_version)
  end

  lane :clean do
    reset_simulators
    xcclean(scheme: "floramoApp")
    clear_derived_data
    clean_build_artifacts
  end

  lane :build_prod_app do
    cert
    sigh(force: true)
    gym(scheme: "floramoApp")
  end
end
